video:
  num_frames: 64
  width: 224
  height: 224
---
model:
  lstm_dim: 400
  fc1_dim: 600
  fc2_dim: 601 # num_freq
---
prepocess:
  train_vids: 'G:/RepNet/data/synthvids/'
  train_vids_size: 100
  test_vids: 'G:/RepNet/data/trainvids'
  test_labels: 'G:/RepNet/data/trainvids/countix_df.csv'
  test_vids_size: 100
  mask_images: 'G:/RepNet/data/masks/'
  mask_layer_num: 3
---
data:
  train_dir: 'G:/RepNet/RepNetData10/'
  test_dir: 'G:/RepNet/RepNetData9/'
---
train:
  train_sample_size: 100
  test_sample_size: 10
  batch_size: 2 #based on your GPU memerory
  epochs: 100
  summary_interval: 1
  checkpoint_interval: 10
---
log:
  chkpt_dir: "ckpt/repnet-mbl.ckpt"
  log_dir: 'logs'
